"""Bot buttons."""

CATALOG_BUTTON = 'catalog'
SUBSCRIBE_BUTTON = 'subscribe'
SUBSCRIBTIONS_BUTTON = 'subscriptions'
BACK_FROM_SUBSCR_BUTTON = 'back'
CANCEL_SUBSCR_BUTTON = 'cancel'
DELETE_BUTTON = 'delete'
SIZE_ALL_BUTTON = 'all'
SIZE_3XS_BUTTON = '3XS'
SIZE_2XS_BUTTON = '2XS'
SIZE_XS_BUTTON = 'XS'
SIZE_S_BUTTON = 'S'
SIZE_M_BUTTON = 'M'
SIZE_L_BUTTON = 'L'
SIZE_XL_BUTTON = 'XL'
SIZE_2XL_BUTTON = '2XL'

available_sizes_list = {
    SIZE_ALL_BUTTON,
    SIZE_3XS_BUTTON,
    SIZE_2XS_BUTTON,
    SIZE_XS_BUTTON,
    SIZE_S_BUTTON,
    SIZE_M_BUTTON,
    SIZE_L_BUTTON,
    SIZE_XL_BUTTON,
    SIZE_2XL_BUTTON,
}
