"""Bot buttons."""

KATALOG_BUTTON = 'catalog'
SUBSCRIBE_BUTTON = 'subscribe'
SUBSCRIBTIONS_BUTTON = 'subscriptions'
SIZE_ALL_BUTTON = 'Все'
SIZE_3XS_BUTTON = '3XS'
SIZE_2XS_BUTTON = '2XS'
SIZE_XS_BUTTON = 'XS'
SIZE_S_BUTTON = 'S'
SIZE_M_BUTTON = 'M'
SIZE_L_BUTTON = 'L'
SIZE_XL_BUTTON = 'XL'
SIZE_2XL_BUTTON = '2XL'
